datafest_profile:
  outputs:
    raw:
      type: snowflake
      account: "eu68469.west-europe.azure"
      user: "INTERSTELLAR"
      database: "DFA23RAWDATA"
      schema: "INTERSTELLAR"
      warehouse: "DFA23"
      password: "N9kXW4oRi"
      role: "INTERSTELLAR"


  target: raw
