name: "DBT Deployment CICD"

on:
  push:
    branches:
      - master

permissions:
  contents: read
  id-token: write

env:
  PYTHON_VERSION: '3.9'
  ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
  USER: ${{ secrets.USER }}
  DATABASE: ${{ secrets.DATABASE }}
  STAGING_SCHEMA: ${{ secrets.STAGING_SCHEMA }}
  DWH: ${{ secrets.DWH }}
  PASSWORD: ${{ secrets.PASSWORD }}
  

jobs:
  dbt_deployment:
    name: "Deploy dbt"
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest.
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup virtual env and install deps
        run: bash helper.sh
        shell: bash
          

      - name: dbt-action
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt test --profiles-dir profiles"
          dbt_project_folder: "datafest_dbt"

      - name: dbt-action
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt run --profiles-dir profiles"
          dbt_project_folder: "datafest_dbt"
